[workspace]
members = [
    "nimbus-core",
    "nimbus-cli",
    "nimbus-contracts",
    "nimbus-sdk",
    "nimbus-node"
]
default-members = ["nimbus-contracts"]
resolver = "2"

[workspace.dependencies]
getrandom = "=0.2.17"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
