[package]
name = "nimbus_contracts"
version = "0.1.0"
edition = "2021"

[lib]
name = "nimbus_contracts"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "nimbus_contracts"
path = "src/main.rs"

[dependencies]
stylus-sdk = "0.10.7"
alloy-primitives = "1.6.0"
alloy-sol-types = "1.6.0"
ark-bls12-381 = "0.6.0"
ark-ec = "0.6.0"
ark-ff = "0.6.0"
ark-serialize = "0.6.0"
sha2 = { version = "0.10.9", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.17", features = ["custom"] }

[features]
export-abi = ["stylus-sdk/export-abi"]
contract-client-gen = []

[dev-dependencies]
rand = "0.8.6"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
