/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface INimbus {
    function init(address owner, address stablecoin_addr, address fee_recipient_addr) external;

    function stablecoin() external view returns (address);

    function feeRecipient() external view returns (address);

    function proposeOwner(address new_owner) external;

    function claimOwnership() external;

    function proposeFeeRecipient(address recipient) external;

    function executeFeeRecipient() external;

    function setExecutionFeeRecipient(address recipient) external;

    function getAccumulatedFees() external view returns (uint256);

    function getExecutionFeeRecipient() external view returns (address);

    function claimExecutionFees(uint256 amount) external returns (bool);

    function totalDepositedPrincipal() external view returns (uint256);

    function ccipRouter() external view returns (address);

    function setCcipRouter(address router) external;

    function pause() external;

    function unpause() external;

    function registerCleanRoot(bytes32 root) external;

    function getCleanRootTimestamp(bytes32 root) external view returns (uint256);

    function registerIssuerKey(bytes calldata pk_iss_bytes) external;

    function revokeIssuerKey(bytes calldata pk_iss_bytes) external;

    function isIssuerKeyTrusted(bytes calldata pk_iss_bytes) external view returns (bool);

    function setCcipSenderAllowlist(uint64 source_chain_selector, bytes calldata sender, bool allowed) external;

    function isCcipSenderAllowed(uint64 source_chain_selector, bytes calldata sender) external view returns (bool);

    function checkLiabilityInvariant() external view;

    function deposit(bytes32 sid, bytes calldata com_k_bytes, uint256 amount) external;

    function revealMaskKey(bytes32 sid, bytes calldata k_bytes, bytes calldata pk_iss_bytes, bytes calldata com_k_bytes) external returns (bool);

    function claimRefund(bytes32 sid) external;

    function spend(bytes32 root, bytes32 nullifier, bytes calldata alpha_neg_bytes, bytes calldata pk_iss_bytes, address recipient, uint256 amount, bytes32 recipient_or_intent_hash, uint256 expiry, bytes32 nonce, uint256 max_execution_fee, uint256 execution_fee) external returns (bool);

    function batchSpend(bytes32[] memory roots, bytes32[] memory nullifiers, bytes[] memory alpha_neg_items, bytes[] memory pk_iss_items, address[] memory recipients, uint256[] memory amounts, bytes32[] memory recipient_or_intent_hashes, uint256[] memory expiries, bytes32[] memory nonces) external returns (bool);

    function spendAndBuyShares(bytes32 root, bytes32 nullifier, bytes calldata alpha_neg_bytes, bytes calldata pk_iss_bytes, address polymarket_ctf, address collateral_token, bytes32 condition_id, uint256 amount, uint256 expiry, bytes32 nonce, uint256 max_execution_fee, uint256 execution_fee) external returns (bool);

    function getFailedIntentRefund(bytes32 nullifier) external view returns (uint256);

    function claimFailedIntentRefund(bytes32 nullifier, address recipient) external returns (bool);

    function ccipReceive(bytes32 message_id, uint64 source_chain_selector, bytes calldata sender, bytes calldata payload) external;

    function verifyGroth16Proof(bytes calldata proof_a_neg_bytes, bytes calldata proof_b_bytes, bytes calldata proof_c_bytes, bytes calldata public_inputs_g1_bytes, bytes calldata vk_alpha_bytes, bytes calldata vk_beta_bytes, bytes calldata vk_gamma_bytes, bytes calldata vk_delta_bytes) external view returns (bool);

    function verifyCompliance(bytes32 root, bytes32 nullifier, address recipient, uint256 amount, bytes calldata proof_a_neg_bytes, bytes calldata proof_b_bytes, bytes calldata proof_c_bytes) external view returns (bool);

    function totalAssets() external returns (uint256);

    function claimAccumulatedYield() external returns (uint256);
}
