//! Groth16 Verifier for PrivateNoteCircuit (BLS12-381, 12 Public Inputs)
//!
//! Implements on-chain verification using EIP-2537 precompiles:
//! - 0x0c (BLS12_G1_MSM): multi-scalar multiplication for public inputs
//! - 0x0b (BLS12_G1_ADD): base IC[0] point addition
//! - 0x0f (BLS12_PAIRING_CHECK): 4-pairing equation check

use alloc::vec::Vec;
use alloy_primitives::FixedBytes;
use stylus_sdk::abi::Bytes;
use stylus_sdk::call::RawCall;

use crate::constants::{BLS12_G1_ADD, BLS12_G1_MSM, BLS12_PAIRING_CHECK};
use crate::storage::Nimbus;

// ─── PrivateNoteCircuit Phase A Trusted Setup VK Constants ─────────────────
// Seed: 0x4E696D6275734E43 (NimbusNC)
// Circuit: PrivateNoteCircuit (13 public inputs) over BLS12-381
// Generated by: generate_note_circuit_evm_vk() in nimbus-core

pub const NOTE_VK_ALPHA_G1: [u8; 128] = alloy_primitives::hex!(
    "0000000000000000000000000000000019d61d4fa8d5d25934b5743baf8770caea160dbef78d2aead0f4adb8fdd72ec9e4a83aaaa4e8212c03dd69ccd77d0c1b0000000000000000000000000000000003d14ce8e3669f979441358f2d5f3ecb7785b533360b46baa39f067a32f5f4a03178af9241e168db27721f1ca662b20e"
);

pub const NOTE_VK_BETA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000007529e9bfb68ff34569ec9bbd8a44b2f25ffff2ac317e3dc4b81357b16dd425f0637732393ed25c8a011eaad12cc00cf0000000000000000000000000000000005aa11b9562355ecebb9ebc63856b7b8289a3192ccc06de36a28e2005d0c0d3e2d75587abac7e704a208f16e04a3112d00000000000000000000000000000000166efaabf3c7d46495c490cd9b13fe56dcd68204ae47b1acffb0a49b32c9625ce809df3eaa0aa0b6b1ca00f7c74637c30000000000000000000000000000000001799c6821e5bc1cee2d0e36e8a98071da1bbe71f4620db49ecb4decd70471793488a5ba1139c7d49ec8586bf7ccf1c9"
);

pub const NOTE_VK_GAMMA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000002c08a3e98e37dc0fe0e57c0c9bdc31e8b3fbd13ef791066f67f9de8884bc86ff8415502952c77ad23519a977176a8290000000000000000000000000000000014e86ff3ef4c990a9a231cffd42aedcbd5b28cff6e5c7cd07c593f841a7253eadcbae9304c3d8acb3be4833c6aaa50ad000000000000000000000000000000000148db9573092cf2f73246b4198cf0e36290fb1ec9c96ebfab84a1f4062515809ce269f2808a3c143276aeb4e8c7caa2000000000000000000000000000000000aecae70a745f07f303772c7cec9ef72d96f40124d4292939e110b92ae0afd3643c70b72bb8db28920add92ff0b577c3"
);

pub const NOTE_VK_DELTA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000017bcbc97d899867d58b26f196bbfdb69dc20e5e422d10244ba118ecd777ed6482b6460f83c9c6f22a5a024c37b34cde40000000000000000000000000000000017bf32dc91b0edb1972d0e58bb7c2fd804f386da5603fa4bc08fb42206bd2b9722cc2b06612a353eb8210b2d7af53e51000000000000000000000000000000000d79d55819650e0c41c968a8cf2c0b21a69ab5b3edb5464135452d95ce50951c9e07646f75bce32b08c95ae97970542f0000000000000000000000000000000013853c26e66af5a7deb9dbb502090959226715250013e38f8a55585065197d99bba8336743d45acebda7cf11e759f381"
);

pub const NOTE_VK_IC: [[u8; 128]; 14] = [
    // IC[0]
    alloy_primitives::hex!("000000000000000000000000000000000b9d2522d320d128526c5774ae121a9ea233276d2411ca411e7f87ca2222cad0ca85fffd5a3cdfc8c466c24b95c1708a000000000000000000000000000000000aa5854239cead955290724687c97f8df593ef4f111eefc711b0f9da07870bc60baeeac9e2bc9cecddbfca3b7313c5a4"),
    // IC[1] - note_root
    alloy_primitives::hex!("0000000000000000000000000000000007f399d13384d21425ce8c7eb80fbd75b9828a49e101379bd1b37b05ce2a927d779c34a582ce7048890c31903cb32cdc000000000000000000000000000000000437b262e409aa61076b9f4595b24326e15186a65c888b4c0b264d2d15ecc213755a9c4ddb95f27edcc4c0d359e23674"),
    // IC[2] - leaf_count (DEC-032)
    alloy_primitives::hex!("000000000000000000000000000000000af6b543aa0ec4239eb7bf40ed0cb6d9deb10a14f6381c901445f5c94dd8a8af0db566f35d0cc0749698eaca1d43679b00000000000000000000000000000000185d2f2393793a596ea11bb78449084996b8545d6462d30f4555a9eec7ea873c6a9e6e001a78ab10735aa3ddca584b8d"),
    // IC[3] - input_nullifier
    alloy_primitives::hex!("0000000000000000000000000000000016766d2fff3ffabc34373e5156fdca0cd58ae15945ed7fc4102f966e43a5d982fb1e5ee3def5c0bdf868364e7f8f9f92000000000000000000000000000000000b7d5cbd3901e774b87815c93e5648cd5e8694c8ed9050754d5817326bc6dd3a17acf034ab3c6fde889d34c9851f779c"),
    // IC[4] - output_commitment
    alloy_primitives::hex!("0000000000000000000000000000000011db4ddf864524c038c9cafdd7191483c2af6f2366d2ccfeca7e985db3774e1132217f9d2ed9c13880395d93b07b3c8600000000000000000000000000000000090ff0aa5cc47d9083f29511f533c94f38cf44de0715be174e199f4356e5d4c94b37499e5987a2d2247a91ef8d543bba"),
    // IC[5] - recipient
    alloy_primitives::hex!("0000000000000000000000000000000000789e66424e07f3051ecc34b2b4f04231427293b63dc49f2cc1eac6decba0cf874a420f5a7f2cd2eb1442c2f3dabc4b0000000000000000000000000000000012da1cc4f60e062a01f9e2f9facf2ad98f3da64a7f387137b9a2b3575923e0cc5bab2aad45b1378530ce66e3e14fab21"),
    // IC[6] - merchant_amount
    alloy_primitives::hex!("0000000000000000000000000000000005cea551622a62f378bba91227f2004eca11b2a6147c14a5ccef14b609e59d7ba05b3ea8fe47189ea1844773aca84723000000000000000000000000000000001584c7ae4dc80a7a5b2c1c69d549b51daacae61dabbff92f94e1eb193f240e39474c5caca3c443ada4da30ab1376eb94"),
    // IC[7] - protocol_fee
    alloy_primitives::hex!("0000000000000000000000000000000003feae34c55f040ed4c1372553466d06e02815b670485be795a7a2e9b87acdf12e884ef3c710e1e56a2111eb6524ce9000000000000000000000000000000000039265c444203f4c811beb3d40bb37d1d02bb2d7d502999f3216bd9e48220158752bd60758c8ad44700bb13ccbd0cfc2"),
    // IC[8] - execution_fee
    alloy_primitives::hex!("000000000000000000000000000000000f6d287b7fc019290dc1a7212478eb6b871f9a7a35019a7e974390d47ab0d927b99b3b7d199efbe0ec634f93a8aa5098000000000000000000000000000000000704002e4377b8e140dcc21489144b2b1a8852b385eb21e5ae3408aea6eea61dad0ff60256cc13ef1de212f687ae2283"),
    // IC[9] - quote_hash
    alloy_primitives::hex!("00000000000000000000000000000000095a6d1401f564cfd3884c6df09cedebb231cbce1f7b78badec8ca5e35a9ac84aa2d46d4f058a16f47d974fef94697a8000000000000000000000000000000000261cf01b0ca5482d32d4497ba714dfa11b0b655b5006d955dc94cfcdd3bdc38533e7e5062aa338c6aa87ad982b9be2b"),
    // IC[10] - chain_id
    alloy_primitives::hex!("0000000000000000000000000000000010da69352ab2e469f50e5051cbdabeb394767cd59ff1976056c6bb8ca8eb206cf051b830aa46753e0f7117c5174480d10000000000000000000000000000000011e9b66bc51a16b00787b068dd961b6a0ebe0d0584d4aa5b331c9fb094600ca4c64ad9955d5cda6be4f421e1fd93ae30"),
    // IC[11] - contract_address
    alloy_primitives::hex!("000000000000000000000000000000000d46df224db9202c73ec766d3b42b3708661ed5bec665ff9fec3544f8e23186399af60e92f967d4388e5640e84e1e8e7000000000000000000000000000000000b041aad676915e862e1fac852d8f3c3bd8b236a0f5d08afeead3b2a847cd4a5f936cdd4a5fde0d2a5de3ef1994555a6"),
    // IC[12] - expiry
    alloy_primitives::hex!("0000000000000000000000000000000013d66dbec8c129e16771e26bf5e89c9d6ad5936d5d2a385c339627aaf21d294017e4e0f204f28630aedad361ca573c9c0000000000000000000000000000000000bb2cedf2775a6e1307fb09b76ccac2fe04c0f2af7d060a6b4ee2dbf0d795816f75adbcc0b76778c6b226a283d1d29b"),
    // IC[13] - has_change
    alloy_primitives::hex!("000000000000000000000000000000000e642b8a2e2498994dc73b9515aa5b0fe35547ec67716f8f9aff7a9ce25b5f27e07a442b7e7b74889bac7db801357b740000000000000000000000000000000004b7a3aed6d6349f4e698cca2e4873d82d46614d69b680ad7dfe14dc6ef5f42e5e23da8e60e512691f6190d8290672b1"),
];

/// Computes the public inputs linear combination point L = IC_0 + sum_{i=1..13} x_i * IC_i in G1.
/// Uses EIP-2537 precompiles 0x0c (BLS12_G1_MSM) and 0x0b (BLS12_G1_ADD).
pub fn compute_note_public_inputs_g1(public_inputs: &[[u8; 32]; 13]) -> Result<[u8; 128], Vec<u8>> {
    let mut msm_input = Vec::with_capacity(13 * 160);
    for i in 0..13 {
        msm_input.extend_from_slice(&NOTE_VK_IC[i + 1]);
        msm_input.extend_from_slice(&public_inputs[i]);
    }

    let host = Nimbus::runtime_host();
    let msm_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_MSM, &msm_input) }
        .map_err(|_| b"G1_MSM_PRECOMPILE_FAILED".to_vec())?;

    if msm_result.len() != 128 {
        return Err(b"INVALID_MSM_RESULT_LENGTH".to_vec());
    }

    // Add base IC[0] point using BLS12_G1_ADD (0x0b)
    let mut add_input = Vec::with_capacity(256);
    add_input.extend_from_slice(&NOTE_VK_IC[0]);
    add_input.extend_from_slice(&msm_result);

    let add_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_ADD, &add_input) }
        .map_err(|_| b"G1_ADD_PRECOMPILE_FAILED".to_vec())?;

    if add_result.len() != 128 {
        return Err(b"INVALID_ADD_RESULT_LENGTH".to_vec());
    }

    let mut out = [0u8; 128];
    out.copy_from_slice(&add_result);
    Ok(out)
}

/// Verifies a Groth16 proof for PrivateNoteCircuit on-chain using EIP-2537 pairing check (0x0f).
/// Equation: e(-A, B) * e(L, gamma) * e(C, delta) * e(alpha, beta) == 1
pub fn verify_private_note_groth16(
    proof_a_neg: &Bytes,
    proof_b: &Bytes,
    proof_c: &Bytes,
    public_inputs_g1: &[u8; 128],
) -> Result<bool, Vec<u8>> {
    if proof_a_neg.len() != 128 || proof_b.len() != 256 || proof_c.len() != 128 {
        return Err(b"INVALID_PROOF_LENGTHS".to_vec());
    }

    // Construct 1536-byte input for BLS12_PAIRING_CHECK (4 pairs)
    let mut input = Vec::with_capacity(1536);
    // Pair 1: -A (G1, 128B) and B (G2, 256B)
    input.extend_from_slice(proof_a_neg);
    input.extend_from_slice(proof_b);
    // Pair 2: L (G1, 128B) and gamma (G2, 256B)
    input.extend_from_slice(public_inputs_g1);
    input.extend_from_slice(&NOTE_VK_GAMMA_G2);
    // Pair 3: C (G1, 128B) and delta (G2, 256B)
    input.extend_from_slice(proof_c);
    input.extend_from_slice(&NOTE_VK_DELTA_G2);
    // Pair 4: alpha (G1, 128B) and beta (G2, 256B)
    input.extend_from_slice(&NOTE_VK_ALPHA_G1);
    input.extend_from_slice(&NOTE_VK_BETA_G2);

    let host = Nimbus::runtime_host();
    let output = unsafe {
        RawCall::new_static(&host)
            .limit_return_data(0, 32)
            .call(BLS12_PAIRING_CHECK, &input)
    }
    .map_err(|_| b"ZK_PAIRING_PRECOMPILE_CALL_FAILED".to_vec())?;

    if output.len() != 32 || output[..31].iter().any(|b| *b != 0) {
        return Err(b"INVALID_PAIRING_OUTPUT".to_vec());
    }

    Ok(output[31] == 1)
}
