//! Groth16 Verifier for PrivateNoteCircuit (BLS12-381, 12 Public Inputs)
//!
//! Implements on-chain verification using EIP-2537 precompiles:
//! - 0x0c (BLS12_G1_MSM): multi-scalar multiplication for public inputs
//! - 0x0b (BLS12_G1_ADD): base IC[0] point addition
//! - 0x0f (BLS12_PAIRING_CHECK): 4-pairing equation check

use alloc::vec::Vec;
use alloy_primitives::FixedBytes;
use stylus_sdk::abi::Bytes;
use stylus_sdk::call::RawCall;

use crate::constants::{BLS12_G1_ADD, BLS12_G1_MSM, BLS12_PAIRING_CHECK};
use crate::storage::Nimbus;

// ─── PrivateNoteCircuit Phase A Trusted Setup VK Constants ─────────────────
// Seed: 0x4E696D6275734E43 (NimbusNC)
// Circuit: PrivateNoteCircuit (15 public inputs) over BLS12-381
// Generated by: generate_note_circuit_evm_vk() in nimbus-core

pub const NOTE_VK_ALPHA_G1: [u8; 128] = alloy_primitives::hex!(
    "0000000000000000000000000000000019d61d4fa8d5d25934b5743baf8770caea160dbef78d2aead0f4adb8fdd72ec9e4a83aaaa4e8212c03dd69ccd77d0c1b0000000000000000000000000000000003d14ce8e3669f979441358f2d5f3ecb7785b533360b46baa39f067a32f5f4a03178af9241e168db27721f1ca662b20e"
);

pub const NOTE_VK_BETA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000007529e9bfb68ff34569ec9bbd8a44b2f25ffff2ac317e3dc4b81357b16dd425f0637732393ed25c8a011eaad12cc00cf0000000000000000000000000000000005aa11b9562355ecebb9ebc63856b7b8289a3192ccc06de36a28e2005d0c0d3e2d75587abac7e704a208f16e04a3112d00000000000000000000000000000000166efaabf3c7d46495c490cd9b13fe56dcd68204ae47b1acffb0a49b32c9625ce809df3eaa0aa0b6b1ca00f7c74637c30000000000000000000000000000000001799c6821e5bc1cee2d0e36e8a98071da1bbe71f4620db49ecb4decd70471793488a5ba1139c7d49ec8586bf7ccf1c9"
);

pub const NOTE_VK_GAMMA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000002c08a3e98e37dc0fe0e57c0c9bdc31e8b3fbd13ef791066f67f9de8884bc86ff8415502952c77ad23519a977176a8290000000000000000000000000000000014e86ff3ef4c990a9a231cffd42aedcbd5b28cff6e5c7cd07c593f841a7253eadcbae9304c3d8acb3be4833c6aaa50ad000000000000000000000000000000000148db9573092cf2f73246b4198cf0e36290fb1ec9c96ebfab84a1f4062515809ce269f2808a3c143276aeb4e8c7caa2000000000000000000000000000000000aecae70a745f07f303772c7cec9ef72d96f40124d4292939e110b92ae0afd3643c70b72bb8db28920add92ff0b577c3"
);

pub const NOTE_VK_DELTA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000017bcbc97d899867d58b26f196bbfdb69dc20e5e422d10244ba118ecd777ed6482b6460f83c9c6f22a5a024c37b34cde40000000000000000000000000000000017bf32dc91b0edb1972d0e58bb7c2fd804f386da5603fa4bc08fb42206bd2b9722cc2b06612a353eb8210b2d7af53e51000000000000000000000000000000000d79d55819650e0c41c968a8cf2c0b21a69ab5b3edb5464135452d95ce50951c9e07646f75bce32b08c95ae97970542f0000000000000000000000000000000013853c26e66af5a7deb9dbb502090959226715250013e38f8a55585065197d99bba8336743d45acebda7cf11e759f381"
);

pub const NOTE_VK_IC: [[u8; 128]; 16] = [
    // IC[0]
    alloy_primitives::hex!("000000000000000000000000000000000cd93140372fb9033aaef00fbe8fcc07e095d9d757918fa8d1a70a8f463042e705825c0f53094bd2b0846502dbd3a27a0000000000000000000000000000000012fecd8ce2c1c357ac1905157b1ef1c9274b07613981ca9cde49179e532a9200276e92cfe15ffe6fdfba713accb9da61"),
    // IC[1] - note_root
    alloy_primitives::hex!("0000000000000000000000000000000001988ee9d0eb3903b137cc7056cdcd6ea21dc70465a14c1d196399014f2f9fa1dd93a46f2113ef1a1abad4602a35a1d500000000000000000000000000000000000a54e173bd074bcc40f85ba1ac31654977ab1d7446bb9bb3c7cd0bf294f82eed53aebead43c3e5ec647c76ec691a4e"),
    // IC[2] - leaf_count (DEC-032)
    alloy_primitives::hex!("0000000000000000000000000000000008c82ce1ef918bae7741db6b07ec3858b2cd6dbcc5e6c0402490fa1a1a5c5805f8f508ce29a4b0a3069d85030ecc3f4b000000000000000000000000000000000f5e0844cd4ee021ed71cb239654d1e4b93bb0f75f6da40096516d441f9e197e5a475abe82c0e14f2e3b1a2a00223291"),
    // IC[3] - input_nullifier
    alloy_primitives::hex!("0000000000000000000000000000000016e52da66c49635d834da956c77b17b86cf54a5bca5eaedf09c92dda3ac3e4573fc2d5f6a3e269f9dcb240ff1753e8180000000000000000000000000000000013ddd90e3af0b13f34b1659d1dc88b3b006a7ffb47241e0f5ce2f51bf1e584b23d204bcca72f6cc47e1ca916111b5301"),
    // IC[4] - note_epoch_id (DEC-033)
    alloy_primitives::hex!("0000000000000000000000000000000015cc10afd3981df1b23ec2ff182b987205956ab38fea2cd68364489a9b4cb52bd84759f79c6e4284cdc9612bfac2bb6d0000000000000000000000000000000003c81bfbd2c5521a0af45f7692817fffc6a94d6287c3ef9107d65f982e46e80cf837b2379c98562b93967ad338488602"),
    // IC[5] - output_commitment
    alloy_primitives::hex!("000000000000000000000000000000000141d3e6ab8034bceec9546097d810ce514eae6ebf7383e2735c2a38e842ac57e037f58f3b6947f29317b7b7fb493c0a0000000000000000000000000000000013ca22327e57cb592cae71f60b27891c61322c78e3a37f8db520f8d1ce27572f6e9f6cad688e4bdf2e0e7776d50af5a3"),
    // IC[6] - recipient
    alloy_primitives::hex!("000000000000000000000000000000001493927532ef1ac5f21bf3072d98a3ecf610df959e99b7ee649d77b47fccd41df8463a721da324e0b8e86eff8c98afbd00000000000000000000000000000000028e30e6f056e5d897b67c7817b9de1fa86239e81e17085c56d9bef16f52e06e64a1a7f995af7faa0ff4c980210ff938"),
    // IC[7] - merchant_amount
    alloy_primitives::hex!("0000000000000000000000000000000013aeec695a1b18a9bb129f5a946faa1b3a4d5994468b53256145759a308af14d4122535bb708aea0ddacc422b6846fd200000000000000000000000000000000125bcb83dff5fc031351edd5de28a524611428e7f56525cd4d712f862b07ce9ab30ad2ee5838fdebeb59445df2e6489a"),
    // IC[8] - protocol_fee
    alloy_primitives::hex!("00000000000000000000000000000000136f1314604c6c01c92bc51457f28b1c045edecf3eb0708996acf4bf050f4fd4ee5093434f9266856848371b810760e000000000000000000000000000000000150d09f035f4e52f59bbb5a910cc19a17927bec076e5be43652dd3880780dcc0b56506da83e7d57eb465b6cfff803f75"),
    // IC[9] - execution_fee
    alloy_primitives::hex!("0000000000000000000000000000000011528375b3802bd94a230cc630809636e51ca5452bdf00c0303aeb4e25b716b557b42e698198cf451755e349441e9972000000000000000000000000000000000672f160e26afa8db769fd2e200e61d2f634a385fd77ce52e52687284ddbfa7083b74cc9717e0249eae41e81623debba"),
    // IC[10] - quote_hash
    alloy_primitives::hex!("00000000000000000000000000000000011fd9bcdbbe177223162380538b7fdd251806b1dc71089824566397e7703e97e9c40ae5f4be22c326d75b36252dfc8e000000000000000000000000000000001416894c3b08d5de82d9896c901c2c04a0f78b3dbab1bbeabb1e4c2aa100c3c4e42f4cc36ffb5644995e2e7ccedd26ba"),
    // IC[11] - chain_id
    alloy_primitives::hex!("0000000000000000000000000000000019d1ed62bd5115727c656458aa4e1e5e1bd4a8cd55b4607b45cce1fd13261741b814dd83bfeddb07a1d567f14975d37d000000000000000000000000000000001635de06b9589e1edb218d6a8052a298098a8c39aae3e1dbe9560640070ffdb54e05c781ba3a499e3eb4f4b2deeb4d56"),
    // IC[12] - contract_address
    alloy_primitives::hex!("00000000000000000000000000000000114d24cf907eae40efd37cf7404f06ad737372d8e1eeaff78e1a78185769b27315a2051305bd1ab2d4d0236ae6d34c780000000000000000000000000000000004969db940c05a5bf439baf34fecfe150e200d283af55ceb9213dda5bd5f1cb00cffdfb05a201d033ed7a90688ee4840"),
    // IC[13] - expiry
    alloy_primitives::hex!("000000000000000000000000000000000c6d68dc0b8c9513680486db9885fe37ce26aa8b49e680c806faf7f19c03437be11ba294798ff5df3b1692dcaedffbd7000000000000000000000000000000001789cfe0e7759145419de386c16e2035ffb71b032155968b152f85fde570d02c32112e5e637088b3a577b81b5eaa30dc"),
    // IC[14] - has_change
    alloy_primitives::hex!("0000000000000000000000000000000002fccad60a623a4301ec8569c39f21b949650cd3e36bca076bcaa25906afb4c228aa99cdecac68f05a9704892cd820a2000000000000000000000000000000001014d270020de7a5669e50e0aaa2776fdb47040ec9c1d6f9e84f954f35369610a1aa60edb634d296029978278ef13a95"),
    // IC[15] - is_rollover (DEC-033)
    alloy_primitives::hex!("0000000000000000000000000000000018236d313b03b48c0ff06f48f22d64c1bdecc45c66537a759a2f6be5a3d0cae20582b9b005bcb939da2270392126c2d200000000000000000000000000000000076a7e60245147d6ddc498a5452a8c8eeead8019f79b63068de7b27b69ec77cd344449cc6b677b6bf84227a459d1acb4"),
];

/// Computes the public inputs linear combination point L = IC_0 + sum_{i=1..15} x_i * IC_i in G1.
/// Uses EIP-2537 precompiles 0x0c (BLS12_G1_MSM) and 0x0b (BLS12_G1_ADD).
pub fn compute_note_public_inputs_g1(public_inputs: &[[u8; 32]; 15]) -> Result<[u8; 128], Vec<u8>> {
    let mut msm_input = Vec::with_capacity(15 * 160);
    for i in 0..15 {
        msm_input.extend_from_slice(&NOTE_VK_IC[i + 1]);
        msm_input.extend_from_slice(&public_inputs[i]);
    }

    let host = Nimbus::runtime_host();
    let msm_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_MSM, &msm_input) }
        .map_err(|_| b"G1_MSM_PRECOMPILE_FAILED".to_vec())?;

    if msm_result.len() != 128 {
        return Err(b"INVALID_MSM_RESULT_LENGTH".to_vec());
    }

    // Add base IC[0] point using BLS12_G1_ADD (0x0b)
    let mut add_input = Vec::with_capacity(256);
    add_input.extend_from_slice(&NOTE_VK_IC[0]);
    add_input.extend_from_slice(&msm_result);

    let add_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_ADD, &add_input) }
        .map_err(|_| b"G1_ADD_PRECOMPILE_FAILED".to_vec())?;

    if add_result.len() != 128 {
        return Err(b"INVALID_ADD_RESULT_LENGTH".to_vec());
    }

    let mut out = [0u8; 128];
    out.copy_from_slice(&add_result);
    Ok(out)
}

/// Verifies a Groth16 proof for PrivateNoteCircuit on-chain using EIP-2537 pairing check (0x0f).
/// Equation: e(-A, B) * e(L, gamma) * e(C, delta) * e(alpha, beta) == 1
pub fn verify_private_note_groth16(
    proof_a_neg: &Bytes,
    proof_b: &Bytes,
    proof_c: &Bytes,
    public_inputs_g1: &[u8; 128],
) -> Result<bool, Vec<u8>> {
    if proof_a_neg.len() != 128 || proof_b.len() != 256 || proof_c.len() != 128 {
        return Err(b"INVALID_PROOF_LENGTHS".to_vec());
    }

    // Construct 1536-byte input for BLS12_PAIRING_CHECK (4 pairs)
    let mut input = Vec::with_capacity(1536);
    // Pair 1: -A (G1, 128B) and B (G2, 256B)
    input.extend_from_slice(proof_a_neg);
    input.extend_from_slice(proof_b);
    // Pair 2: L (G1, 128B) and gamma (G2, 256B)
    input.extend_from_slice(public_inputs_g1);
    input.extend_from_slice(&NOTE_VK_GAMMA_G2);
    // Pair 3: C (G1, 128B) and delta (G2, 256B)
    input.extend_from_slice(proof_c);
    input.extend_from_slice(&NOTE_VK_DELTA_G2);
    // Pair 4: alpha (G1, 128B) and beta (G2, 256B)
    input.extend_from_slice(&NOTE_VK_ALPHA_G1);
    input.extend_from_slice(&NOTE_VK_BETA_G2);

    let host = Nimbus::runtime_host();
    let output = unsafe {
        RawCall::new_static(&host)
            .limit_return_data(0, 32)
            .call(BLS12_PAIRING_CHECK, &input)
    }
    .map_err(|_| b"ZK_PAIRING_PRECOMPILE_CALL_FAILED".to_vec())?;

    if output.len() != 32 || output[..31].iter().any(|b| *b != 0) {
        return Err(b"INVALID_PAIRING_OUTPUT".to_vec());
    }

    Ok(output[31] == 1)
}
