//! Groth16 Verifier for PrivateNoteCircuit (BLS12-381, 12 Public Inputs)
//!
//! Implements on-chain verification using EIP-2537 precompiles:
//! - 0x0c (BLS12_G1_MSM): multi-scalar multiplication for public inputs
//! - 0x0b (BLS12_G1_ADD): base IC[0] point addition
//! - 0x0f (BLS12_PAIRING_CHECK): 4-pairing equation check

use alloc::vec::Vec;
use alloy_primitives::FixedBytes;
use stylus_sdk::abi::Bytes;
use stylus_sdk::call::RawCall;

use crate::constants::{BLS12_G1_ADD, BLS12_G1_MSM, BLS12_PAIRING_CHECK};
use crate::storage::Nimbus;

// ─── PrivateNoteCircuit Phase A Trusted Setup VK Constants ─────────────────
// Seed: 0x4E696D6275734E43 (NimbusNC)
// Circuit: PrivateNoteCircuit (12 public inputs) over BLS12-381
// Generated by: generate_note_circuit_evm_vk() in nimbus-core

pub const NOTE_VK_ALPHA_G1: [u8; 128] = alloy_primitives::hex!(
    "0000000000000000000000000000000019d61d4fa8d5d25934b5743baf8770caea160dbef78d2aead0f4adb8fdd72ec9e4a83aaaa4e8212c03dd69ccd77d0c1b0000000000000000000000000000000003d14ce8e3669f979441358f2d5f3ecb7785b533360b46baa39f067a32f5f4a03178af9241e168db27721f1ca662b20e"
);

pub const NOTE_VK_BETA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000007529e9bfb68ff34569ec9bbd8a44b2f25ffff2ac317e3dc4b81357b16dd425f0637732393ed25c8a011eaad12cc00cf0000000000000000000000000000000005aa11b9562355ecebb9ebc63856b7b8289a3192ccc06de36a28e2005d0c0d3e2d75587abac7e704a208f16e04a3112d00000000000000000000000000000000166efaabf3c7d46495c490cd9b13fe56dcd68204ae47b1acffb0a49b32c9625ce809df3eaa0aa0b6b1ca00f7c74637c30000000000000000000000000000000001799c6821e5bc1cee2d0e36e8a98071da1bbe71f4620db49ecb4decd70471793488a5ba1139c7d49ec8586bf7ccf1c9"
);

pub const NOTE_VK_GAMMA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000002c08a3e98e37dc0fe0e57c0c9bdc31e8b3fbd13ef791066f67f9de8884bc86ff8415502952c77ad23519a977176a8290000000000000000000000000000000014e86ff3ef4c990a9a231cffd42aedcbd5b28cff6e5c7cd07c593f841a7253eadcbae9304c3d8acb3be4833c6aaa50ad000000000000000000000000000000000148db9573092cf2f73246b4198cf0e36290fb1ec9c96ebfab84a1f4062515809ce269f2808a3c143276aeb4e8c7caa2000000000000000000000000000000000aecae70a745f07f303772c7cec9ef72d96f40124d4292939e110b92ae0afd3643c70b72bb8db28920add92ff0b577c3"
);

pub const NOTE_VK_DELTA_G2: [u8; 256] = alloy_primitives::hex!(
    "0000000000000000000000000000000017bcbc97d899867d58b26f196bbfdb69dc20e5e422d10244ba118ecd777ed6482b6460f83c9c6f22a5a024c37b34cde40000000000000000000000000000000017bf32dc91b0edb1972d0e58bb7c2fd804f386da5603fa4bc08fb42206bd2b9722cc2b06612a353eb8210b2d7af53e51000000000000000000000000000000000d79d55819650e0c41c968a8cf2c0b21a69ab5b3edb5464135452d95ce50951c9e07646f75bce32b08c95ae97970542f0000000000000000000000000000000013853c26e66af5a7deb9dbb502090959226715250013e38f8a55585065197d99bba8336743d45acebda7cf11e759f381"
);

pub const NOTE_VK_IC: [[u8; 128]; 13] = [
    // IC[0]
    alloy_primitives::hex!("000000000000000000000000000000001392c2f671768e8067e3ac505c309dadd1dbe0173b389e1ffb2ec0bb7d9a1da5760dc34adfe8ad95386f1c663198e19f000000000000000000000000000000000e53a8df746ad278423f9988c1ec5a84e38a0b0f93a6a27f07691fd108e8d74a42c78018dbe48316e2d4e97491c0e4d2"),
    // IC[1] - note_root
    alloy_primitives::hex!("000000000000000000000000000000000b43d521f35048f2762cbce2b9824d9e6c95e8baea3a4f4b1c71e765b44870f902006038bec86b648e6c0b3892eb59c2000000000000000000000000000000001736ac2975806126ce86a241364043f48aaf234e5fa7b94775d85b52d3287dffdce5f11216e7b0e655bb8c76cd1f8555"),
    // IC[2] - input_nullifier
    alloy_primitives::hex!("0000000000000000000000000000000005a728b32aa18617a758620a93dffe1a006060371e58bab14154fd8d79bdaf270dca3ea7353909158c7b7ee8d87fdb0c000000000000000000000000000000000166cf28becbe3d3eb3cb5d5a6630a2361fc09ce9af52384dec73d0b636bb4f69837d6ac02540eb36f32c1621b443c7a"),
    // IC[3] - output_commitment
    alloy_primitives::hex!("000000000000000000000000000000001935c42a87b1e2d3d5fe3851ec16f162dda4181dd255f29ed6842e4eec56d5781135973f60db6623ae6cf5477597ffac000000000000000000000000000000000fad3e540b9b3c23db7e683a9f7845df253edff4a87d4720c8f64c1a9d06c82c11d50b6bad099b1c527556f936c0e759"),
    // IC[4] - recipient
    alloy_primitives::hex!("00000000000000000000000000000000111a80fd72d2b71f101cfe04d2867d45ba76b12a05fe58b79de108ca0e897564e3e9c706b25a4812ace61ab733cb24c000000000000000000000000000000000005bcdb5fabd0251d824b8f41d37bec81b419af4c66a49880d77c2e5971e64b35a5f808dd69edd33c4661b84e2cb66ef"),
    // IC[5] - merchant_amount
    alloy_primitives::hex!("000000000000000000000000000000000be017869f09448cba66c64e2de5a8500904615db631f71f0ae3c4a48d1670a026dd02665984adc63a5752407f380c0c000000000000000000000000000000000bff517e2671c11ec7c0287e8c0fa4d2a7ad06af85c526ad0f6be28f9147811bec81b90c14157b3c55709ba32ae21bf0"),
    // IC[6] - protocol_fee
    alloy_primitives::hex!("000000000000000000000000000000000ccc504ac168280c7acaa25c1fe5f97b583bf448d128f752dcdeffe35f2d15e5b2c7088f02eebf4b66a28f79f3617c7e00000000000000000000000000000000095b335e3cf65a155e0f61e3ef20bfce2b1b7edf28079a3f0925dcb1aa66f8b38bc6ace8ffee24ca1ee2e2f96d61e5e6"),
    // IC[7] - execution_fee
    alloy_primitives::hex!("00000000000000000000000000000000099c5898ed5cd23e400bb9f348cf9851c13819d0a6ed66aa0de2e3bf861a40dea24bc4aa9a99a8e53dddac3e435b9f41000000000000000000000000000000001386ae6702b3af51f3014828e6229489dbc83a10c9f5f317dbefc9a8e44736f4e7c0ab5465ea209da7fdf9fad8e8d72b"),
    // IC[8] - quote_hash
    alloy_primitives::hex!("0000000000000000000000000000000014139467d2f73d6c63068c90bfca3f312cb1891b549c17b1d8d14afd77cc020a181f461b7af8bd910054b922b882004200000000000000000000000000000000009cb8e8b49d35721dcbf34954a14534a9c3a4099ddc5d1f354481ea32378772bc95d44421294dbd36a81d9eb7e5aec5"),
    // IC[9] - chain_id
    alloy_primitives::hex!("000000000000000000000000000000000a7e720e610375bb2295d19df319be7529532dfc272377ba6aa928ccb41d07bba0d33e53fe9a67f827634c9a61d65353000000000000000000000000000000000523e8c60c228d1b215c11cbbb9f2aae7fd3234a56ea3c1e40837f70293592ff370567bb61afe9d5d4dda88657966c46"),
    // IC[10] - contract_address
    alloy_primitives::hex!("0000000000000000000000000000000000a51bb1bfdd1eb806011d39d9b313f857f47c2b04c361ae650f7970b60685990efe83a6157a210c9a50616e0b09b0150000000000000000000000000000000019e6a43f3e65d24b3c39730efb8ebf6a4343295fbbea44b7ff8de00ae35883b0d3a9368590f6ca2728d013a3e6b6b788"),
    // IC[11] - expiry
    alloy_primitives::hex!("000000000000000000000000000000000d500118a30f40be48f4ec5597d2f509235b2843cad5832d733eb95f4e229e895f19e85f80d0904b6d97b893113b44aa0000000000000000000000000000000001079eb5219d0d21180d97acaca2f49f8ebe89960e7f7abaccf46ce6cb56f303192fdc90576f10394678d7518bed6c8c"),
    // IC[12] - has_change
    alloy_primitives::hex!("000000000000000000000000000000000a3ee93ede5c02af4cbd84924fc353a41e4c8375cde9a1ddadbfa52d8de4efe91567b5906f9a2297abbe49dee928adff0000000000000000000000000000000015746e747ff8ee04b4de1ce25cceb1cf602c7a6e2616719ed5125fe8bcb7875708246cbe1bb35fa503636f2421d9ee6b"),
];

/// Computes the public inputs linear combination point L = IC_0 + sum_{i=1..12} x_i * IC_i in G1.
/// Uses EIP-2537 precompiles 0x0c (BLS12_G1_MSM) and 0x0b (BLS12_G1_ADD).
pub fn compute_note_public_inputs_g1(public_inputs: &[[u8; 32]; 12]) -> Result<[u8; 128], Vec<u8>> {
    let mut msm_input = Vec::with_capacity(12 * 160);
    for i in 0..12 {
        msm_input.extend_from_slice(&NOTE_VK_IC[i + 1]);
        msm_input.extend_from_slice(&public_inputs[i]);
    }

    let host = Nimbus::runtime_host();
    let msm_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_MSM, &msm_input) }
        .map_err(|_| b"G1_MSM_PRECOMPILE_FAILED".to_vec())?;

    if msm_result.len() != 128 {
        return Err(b"INVALID_MSM_RESULT_LENGTH".to_vec());
    }

    // Add base IC[0] point using BLS12_G1_ADD (0x0b)
    let mut add_input = Vec::with_capacity(256);
    add_input.extend_from_slice(&NOTE_VK_IC[0]);
    add_input.extend_from_slice(&msm_result);

    let add_result = unsafe { RawCall::new_static(&host).call(BLS12_G1_ADD, &add_input) }
        .map_err(|_| b"G1_ADD_PRECOMPILE_FAILED".to_vec())?;

    if add_result.len() != 128 {
        return Err(b"INVALID_ADD_RESULT_LENGTH".to_vec());
    }

    let mut out = [0u8; 128];
    out.copy_from_slice(&add_result);
    Ok(out)
}

/// Verifies a Groth16 proof for PrivateNoteCircuit on-chain using EIP-2537 pairing check (0x0f).
/// Equation: e(-A, B) * e(L, gamma) * e(C, delta) * e(alpha, beta) == 1
pub fn verify_private_note_groth16(
    proof_a_neg: &Bytes,
    proof_b: &Bytes,
    proof_c: &Bytes,
    public_inputs_g1: &[u8; 128],
) -> Result<bool, Vec<u8>> {
    if proof_a_neg.len() != 128 || proof_b.len() != 256 || proof_c.len() != 128 {
        return Err(b"INVALID_PROOF_LENGTHS".to_vec());
    }

    // Construct 1536-byte input for BLS12_PAIRING_CHECK (4 pairs)
    let mut input = Vec::with_capacity(1536);
    // Pair 1: -A (G1, 128B) and B (G2, 256B)
    input.extend_from_slice(proof_a_neg);
    input.extend_from_slice(proof_b);
    // Pair 2: L (G1, 128B) and gamma (G2, 256B)
    input.extend_from_slice(public_inputs_g1);
    input.extend_from_slice(&NOTE_VK_GAMMA_G2);
    // Pair 3: C (G1, 128B) and delta (G2, 256B)
    input.extend_from_slice(proof_c);
    input.extend_from_slice(&NOTE_VK_DELTA_G2);
    // Pair 4: alpha (G1, 128B) and beta (G2, 256B)
    input.extend_from_slice(&NOTE_VK_ALPHA_G1);
    input.extend_from_slice(&NOTE_VK_BETA_G2);

    let host = Nimbus::runtime_host();
    let output = unsafe {
        RawCall::new_static(&host)
            .limit_return_data(0, 32)
            .call(BLS12_PAIRING_CHECK, &input)
    }
    .map_err(|_| b"ZK_PAIRING_PRECOMPILE_CALL_FAILED".to_vec())?;

    if output.len() != 32 || output[..31].iter().any(|b| *b != 0) {
        return Err(b"INVALID_PAIRING_OUTPUT".to_vec());
    }

    Ok(output[31] == 1)
}
