[package]
name = "nimbus-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.6.0"
ark-ec = "0.6.0"
ark-ff = "0.6.0"
ark-std = "0.6.0"
ark-serialize = "0.6.0"
ark-groth16 = "0.6.0"
ark-relations = "0.6.0"
ark-poly = "0.6.0"
ark-r1cs-std = "0.6.0"
ark-snark = "0.6.0"
rand = "0.10.3"
sha2 = "0.10.9"
sha3 = "0.10.9"
digest = "0.10.7"
rayon = "1.12.0"
hex = "0.4.3"
