//! Blind signature protocol commands

use nimbus_core::*;
use rand::Rng;

pub fn blind<R: Rng>(message: String, rng: &mut R) {
    let (blinded_msg, r) = client_blind(message.as_bytes(), rng);
    
    let blinded_hex = hex::encode(serialize_to_bytes(&blinded_msg));
    let r_hex = hex::encode(serialize_to_bytes(&r));
    
    println!("MESSAGE BLINDED");
    println!("------------------------------------------------------------");
    println!("Blinded Message (X) :\n{}", blinded_hex);
    println!("\nBlinding Factor (r) :\n{}", r_hex);
    println!("------------------------------------------------------------");
}

pub fn sign<R: Rng>(blinded: String, sk: String, rng: &mut R) {
    let blinded_bytes = hex::decode(blinded).expect("Invalid blinded message hex");
    let sk_bytes = hex::decode(sk).expect("Invalid secret key hex");
    
    let blinded_msg: BlindedMessage = deserialize_from_bytes(&blinded_bytes)
        .expect("Failed to deserialize blinded message");
    let sk_iss: IssuerSecretKey = deserialize_from_bytes(&sk_bytes)
        .expect("Failed to deserialize secret key");
        
    let (masked_sig, k, com_k) = issuer_sign_blinded(&sk_iss, &blinded_msg, rng);
    
    let masked_sig_hex = hex::encode(serialize_to_bytes(&masked_sig));
    let k_hex = hex::encode(serialize_to_bytes(&k));
    let com_k_hex = hex::encode(serialize_to_bytes(&com_k));
    
    println!("MASKED SIGNATURE GENERATED BY ISSUER");
    println!("------------------------------------------------------------");
    println!("Masked Signature (sigma_tilde) :\n{}", masked_sig_hex);
    println!("\nMasking Key (k)               :\n{}", k_hex);
    println!("\nCommitment (com_k)            :\n{}", com_k_hex);
    println!("------------------------------------------------------------");
}

pub fn verify_masked(blinded: String, com_k: String, masked_sig: String) {
    let blinded_bytes = hex::decode(blinded).expect("Invalid blinded message hex");
    let com_k_bytes = hex::decode(com_k).expect("Invalid commitment hex");
    let masked_sig_bytes = hex::decode(masked_sig).expect("Invalid masked signature hex");
    
    let x: BlindedMessage = deserialize_from_bytes(&blinded_bytes)
        .expect("Failed to deserialize blinded message");
    let commitment: MaskingKeyCommitment = deserialize_from_bytes(&com_k_bytes)
        .expect("Failed to deserialize commitment");
    let sig: MaskedBlindSignature = deserialize_from_bytes(&masked_sig_bytes)
        .expect("Failed to deserialize masked signature");
        
    let is_valid = client_verify_masked(&x, &commitment, &sig);
    
    println!("VERIFY MASKED SIGNATURE (OFF-CHAIN)");
    println!("------------------------------------------------------------");
    if is_valid {
        println!("VALID: Masked signature matches blinded message and commitment!");
    } else {
        println!("INVALID: Signature verification failed!");
    }
    println!("------------------------------------------------------------");
}

pub fn unmask(masked_sig: String, r: String, k: String) {
    let sig_bytes = hex::decode(masked_sig).expect("Invalid masked signature hex");
    let r_bytes = hex::decode(r).expect("Invalid blinding factor hex");
    let k_bytes = hex::decode(k).expect("Invalid masking key hex");
    
    let sig: MaskedBlindSignature = deserialize_from_bytes(&sig_bytes)
        .expect("Failed to deserialize masked signature");
    let r_factor: BlindingFactor = deserialize_from_bytes(&r_bytes)
        .expect("Failed to deserialize blinding factor");
    let k_key: MaskingKey = deserialize_from_bytes(&k_bytes)
        .expect("Failed to deserialize masking key");
        
    let unmasked_sig = client_unmask(&sig, &r_factor, &k_key)
        .expect("Failed to compute unmask key inverse");
        
    let unmasked_hex = hex::encode(serialize_to_bytes(&unmasked_sig));
    
    println!("SIGNATURE UNMASKED SUCCESSFULLY");
    println!("------------------------------------------------------------");
    println!("Unmasked Signature (alpha) :\n{}", unmasked_hex);
    println!("------------------------------------------------------------");
}

pub fn verify(message: String, sig: String, pk: String) {
    let sig_bytes = hex::decode(sig).expect("Invalid signature hex");
    let pk_bytes = hex::decode(pk).expect("Invalid public key hex");
    
    let signature: UnmaskedSignature = deserialize_from_bytes(&sig_bytes)
        .expect("Failed to deserialize signature");
    let pk_iss: IssuerPublicKey = deserialize_from_bytes(&pk_bytes)
        .expect("Failed to deserialize public key");
        
    let is_valid = verify_unmasked(message.as_bytes(), &signature, &pk_iss);
    
    println!("VERIFY FINAL UNBLINDED SIGNATURE");
    println!("------------------------------------------------------------");
    if is_valid {
        println!("VALID: The signature is verified and authentic under the Issuer's Public Key!");
    } else {
        println!("INVALID: Signature verification failed!");
    }
    println!("------------------------------------------------------------");
}
